name: Release

env:
  DOTNET_NOLOGO: true

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "src/**/*.cs"
      - "src/**/*.csproj"

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: { fetch-depth: 0 }

      - name: Setup NerdBank.GitVersioning
        uses: dotnet/nbgv@v0.4
        with: { setAllVars: true }

      - name: Build
        working-directory: src/ViewBindingsGenerator
        run: |
          dotnet build -c Release

      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.NBGV_SemVer2 }}
          release_name: ${{ env.NBGV_SemVer2 }}

      - name: Publish to NuGet
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
          SOURCE_URL: https://api.nuget.org/v3/index.json
        run: |
          dotnet nuget push **/*.nupkg --skip-duplicate -s ${{ env.SOURCE_URL }} -k ${{ env.NUGET_AUTH_TOKEN }}
